/*******************************************************************************
 * Copyright (C) 2017 Daniele Pallastrelli
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

"use strict"

//////////////////////////////////////////////////////////////////
// WsClient

// public methods:

function WsClient(wsAdd, connectionHandler) {

    var self = this;

    this.service = null;

    function connect() {
        self.service = new WebSocket(wsAdd);
        self.service.onmessage = function (event) {
            eval(event.data);
            // const result = eval(event.data);
            // self.service.send(result);
        };
        self.service.onopen = function () {
            console.log('WS connected');
            connectionHandler(true);
        };
        self.service.onclose = function () {
            console.log('WS closed');
            connectionHandler(false);
            setTimeout(function () {
                console.log('trying to reconnect');
                connect();
            }, 1000);
        };
        self.service.onerror = function () {
            console.log('WS error');
            self.service.close();
        };
    }

    connect();
}

/*
Acp.prototype.disconnect = function() {
    if (this.service == null) return;
    this.service.close();
    this.service = null;
}
*/

WsClient.prototype.send = function (msg) {
    if (this.service == null) return;

    if (this.service.readyState === this.service.OPEN)
        this.service.send(msg);
}

WsClient.prototype.sendObj = function (obj) {
    //console.log('sending %o', obj);
    const msg = JSON.stringify(obj);
    this.send(msg);
}

////////////////////////////////////////////////////////////

// connection

var proxy = null;

function connect() {
    const ip = "localhost";
    const port = "9971";

    const add = 'ws://' + ip + ':' + port;
    console.log('using ws address: ' + add);
    proxy = new WsClient(add, function (connected) {
        if (connected) console.log('connected');
        else console.log('disconnected');
    });
}

// init

$(function () {

    connect();

    // buttons
    var buttons = document.getElementsByTagName('button');
    for (var i = 0; i < buttons.length; i++) {
        var button = buttons[i];
        button.onclick = function () {
            const ev = {
                event: 'onclick',
                id: this.id
            };
            proxy.sendObj(ev);
        };
    }

    // input (sliders & checkboxes)
    var inputs = document.getElementsByTagName('input');
    for (var i = 0; i < inputs.length; i++) {
        var slider = inputs[i];
        slider.oninput = function () {
            const ev = {
                event: 'oninput',
                value: this.value,
                id: this.id
            };
            proxy.sendObj(ev);
        };
        slider.onclick = function () {
            const ev = {
                event: 'onclick',
                id: this.id
            };
            proxy.sendObj(ev);
        };
    }

});